package Vistas.Forms;

import Controlador.AccidenteDAO;
import Modelo.Accidente;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class Historial extends javax.swing.JPanel {

    //Clasees que contienen los metodos para manejar la DB
    AccidenteDAO accidente = new AccidenteDAO();
    Accidente p = new Accidente();

    public Historial() {
        initComponents();
        setOpaque(false);
        setVisible(true);

        //Agregando imagen para el boton siguiente y redimensionandolo
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/icon/siguiente.png"));

        // Escalar la imagen al tamaño deseado (ajustar valores segun se necesite)
        Image imagen = icono.getImage();
        Image nuevaImagen = imagen.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(nuevaImagen));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        PanelDatosEpidemiologicos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha_accidente = new javax.swing.JTextField();
        box_causa_accidente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mecanismo_accidente = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_hora_accidente = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        box_pariente = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        box_lugar = new javax.swing.JComboBox<>();
        box_tratamiento_inicial = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_registro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        PanelDatosClinicos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        box_area_quemadura = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_porcentaje = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        PanelDatosEpidemiologicos.setBackground(new java.awt.Color(0, 102, 102));
        PanelDatosEpidemiologicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATOS EPIDEMIOLOGICOS");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CAUSA DEL ACCIDENTE:");

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MECANISMO DEL ACCIDENTE:");

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FECHA EN QUE OCURRIO EL ACCIDENTE:");

        txt_fecha_accidente.setBackground(new java.awt.Color(204, 204, 204));
        txt_fecha_accidente.setForeground(new java.awt.Color(0, 0, 0));

        box_causa_accidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liquido Caliente", "Caida", "Inmersión", "Fuego o flama", "Pólvora", "Explosión", "Fuego", "Electricidad", "Quimicos", "Contacto Objetos Calientes", "Fricción", "Desconoce", "Otros" }));

        txt_mecanismo_accidente.setColumns(20);
        txt_mecanismo_accidente.setRows(5);
        jScrollPane1.setViewportView(txt_mecanismo_accidente);

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HORA EN QUE OCURRIO EL ACCIDENTE:");

        txt_hora_accidente.setBackground(new java.awt.Color(204, 204, 204));
        txt_hora_accidente.setForeground(new java.awt.Color(0, 0, 0));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CON QUIEN SE ENCONTRABA EN EL MOMENTO DEL ACCIDENTE:");

        box_pariente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mamá", "Papá", "Abuelos", "Hermanos", "Tíos", "Otros" }));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LUGAR DONDE OCURRIO EL ACCIDENTE:");

        box_lugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala", "Comedor", "Cocina", "Baño", "Dormitorio", "Centro de Estudios", "Cent. Recreación", "Patio", "Vía Publica", "Techo de Casa", "Un solo cuarto", "Otro Lugar" }));

        box_tratamiento_inicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua", "Aceite", "Tierra", "Crema", "Pasta Dental", "Huevo", "Quito Ropa", "Nada", "Otro" }));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TRATAMIENTO INICIAL DADO EN CASA:");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO MEDICO:");

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");

        javax.swing.GroupLayout PanelDatosEpidemiologicosLayout = new javax.swing.GroupLayout(PanelDatosEpidemiologicos);
        PanelDatosEpidemiologicos.setLayout(PanelDatosEpidemiologicosLayout);
        PanelDatosEpidemiologicosLayout.setHorizontalGroup(
            PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jLabel7))
                    .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fecha_accidente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_hora_accidente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_causa_accidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(box_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_pariente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(box_tratamiento_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelDatosEpidemiologicosLayout.setVerticalGroup(
            PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(box_causa_accidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(PanelDatosEpidemiologicosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_fecha_accidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_hora_accidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(box_pariente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(box_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDatosEpidemiologicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(box_tratamiento_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelDatosClinicos.setBackground(new java.awt.Color(0, 102, 102));
        PanelDatosClinicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ÁREA DE QUEMADURA:");

        btnSiguiente.setBackground(new java.awt.Color(46, 68, 82));
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATOS CLINICOS");

        box_area_quemadura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabeza", "Cara", "Cuello", "Espalda", "Abdomen", "T.A. c/m", "T.A. s/mm", "Glúteos", "R. Perineal", "Genitales", "Hombro", "Muñeca", "Palmar", "Dorsal", "Digital", "Mano Izquierda", "Mano Derecha", "Pie Izquierdo", "Pie Derecho", "E. Superior Izquierda", "E. Superior Derecha", "E. Inferior Izquierda", "E. Inferior Derecha" }));

        table_porcentaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cabeza", "19", "17", "13", "11", "9", "7", null},
                {"Cuello", "2", "2", "2", "2", "2", "2", null},
                {"Tronco Anterior", "13", "13", "13", "13", "13", "13", null},
                {"Tronco Posterior", "13", "13", "13", "13", "13", "13", null},
                {"Cada Glúteo", "2 1/2", "2 1/2", "2 1/2", "2 1/2", "2 1/2", "2 1/2", null},
                {"Genitales", "1", "1", "1", "1", "1", "1", null},
                {"Cada Brazo", "4", "4", "4", "4", "4", "4", null},
                {"Cada Antebrazo", "3", "3", "3", "3", "3", "3", null},
                {"Cada Mano", "2 1/2", "2 1/2", "2 1/2", "2 1/2", "2 1/2", "2 1/2", null},
                {"Cada Muslo", "5 1/2", "6 1/2", "8", "8 1/2", "9", "9 1/2", null},
                {"Cada Pierna", "5", "5", "5 1/2", "6", "6 1/2", "7", null},
                {"Cada Pie", "3 1/2", "3 1/2", "3 1/2", "3 1/2", "3 1/2", "3 1/2", null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Area", "1a", "1-4 a", "5-9 a", "10-14 a", "15 a 20", "Adulto", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_porcentaje);

        javax.swing.GroupLayout PanelDatosClinicosLayout = new javax.swing.GroupLayout(PanelDatosClinicos);
        PanelDatosClinicos.setLayout(PanelDatosClinicosLayout);
        PanelDatosClinicosLayout.setHorizontalGroup(
            PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                .addGroup(PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_area_quemadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatosClinicosLayout.setVerticalGroup(
            PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                .addGroup(PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                        .addGroup(PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosClinicosLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(PanelDatosClinicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(box_area_quemadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDatosClinicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDatosEpidemiologicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDatosEpidemiologicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelDatosClinicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        showForm();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void showForm() {
        // Obtener el contenedor principal que contiene este panel Historial
        Container contenedorPrincipal = SwingUtilities.getWindowAncestor(this);
        // Comprobar que el contenedor principal es un JFrame
        if (contenedorPrincipal instanceof JFrame) {
            // Ocultar este panel Historial
            this.setVisible(false);

            // Crear una instancia del panel Historial2
            Historial2 historial2 = new Historial2();

            // Agregar el panel Historial2 al contenedor principal
            contenedorPrincipal.add(historial2);

            // Asegurarse de que el panel Historial2 sea visible
            historial2.setVisible(true);

            // Revalidar y repintar el contenedor principal
            contenedorPrincipal.revalidate();
            contenedorPrincipal.repaint();
        }
    }
    //metodo para agregar.
    /*void agregar() {

        try {
            // Obtener la fecha desde el JTextField
            String fechaIngresoHStr = txtFechaIngresoH.getText();
            String fechaIngresoUnidad = txtFechaIngresoQ.getText();
            String fechaEgresoUnidad = txtFechaEgresoQ.getText();
            String fechaNacimiento = txtFechaNacimiento.getText();

            // Convertir la cadena de texto a LocalDate
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate fechaIngresoH = LocalDate.parse(fechaIngresoHStr, formatter);
            LocalDate fechaIngresoQ = LocalDate.parse(fechaIngresoUnidad, formatter);
            LocalDate fechaEgresoQ = LocalDate.parse(fechaEgresoUnidad, formatter);
            LocalDate fechaNacim = LocalDate.parse(fechaNacimiento, formatter);

            //Array para almacenar los valores de todos los TextFields 
            Object[] ob = new Object[]{
                txtRegistro.getText(), fechaIngresoH, fechaIngresoQ,
                fechaEgresoQ, txtNombrePaciente.getText(), txtApellidosPaciente.getText(),
                Integer.parseInt(txtEdad.getText()), (String) txtSexo.getSelectedItem(),
                fechaNacim, txtDireccion.getText(), txtAldea.getText(),
                txtMunicipio.getText(), txtDepartamento.getText(), Integer.parseInt(txtTelefono.getText()),
                Integer.parseInt(txtNoMiembros.getText()), Integer.parseInt(txtAdultos.getText()),
                Integer.parseInt(txtNinos.getText()), Integer.parseInt(txtNoHijos.getText()), Integer.parseInt(txtLugarOcupa.getText()),
                opcionSeleccionada, txtReferido.getText(), txtEncargado.getText(),
                txtParentesco.getText(), Integer.parseInt(txtEdadEncargado.getText()),
                (String) txtEscolaridad.getSelectedItem(), txtOcupacion.getText()
            };

            paciente.agregar(ob);
            //Revisa si el campo de Registro medico esta vacio, y lanza error si es asi. 
            if (txtRegistro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El campo 'Registro Médico' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                //Si todo esta correcto se lanza un mensaje de afirmacion y se limpian los campos 
                JOptionPane.showMessageDialog(null, "Paciente Registrado con exito!");
                limpiarCampos();
            }
        } catch (Exception e) {
            // Si hay una excepción, mostrar un cuadro de diálogo de error
            JOptionPane.showMessageDialog(null, "Error al registrar al paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprimir la traza de la excepción en la consola (puedes quitar esto en producción)
        }

    }*/
    //metodo para limpiar los campos
    /*void limpiarCampos() {
        txtRegistro.setText("");
        txtFechaIngresoH.setText("");
        txtFechaIngresoQ.setText("");
        txtFechaEgresoQ.setText("");
        txtNombrePaciente.setText("");
        txtApellidosPaciente.setText("");
        txtEdad.setText("");
        txtSexo.setSelectedIndex(0);
        txtFechaNacimiento.setText("");
        txtDireccion.setText("");
        txtAldea.setText("");
        txtMunicipio.setText("");
        txtDepartamento.setText("");
        txtTelefono.setText("");
        txtNoMiembros.setText("");
        txtAdultos.setText("");
        txtNinos.setText("");
        txtNoHijos.setText("");
        txtLugarOcupa.setText("");
        buttonGroup.clearSelection();
        txtReferido.setText("");
        txtEncargado.setText("");
        txtParentesco.setText("");
        txtEdadEncargado.setText("");
        txtEscolaridad.setSelectedIndex(0);
        txtOcupacion.setText("");
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatosClinicos;
    private javax.swing.JPanel PanelDatosEpidemiologicos;
    private javax.swing.JComboBox<String> box_area_quemadura;
    private javax.swing.JComboBox<String> box_causa_accidente;
    private javax.swing.JComboBox<String> box_lugar;
    private javax.swing.JComboBox<String> box_pariente;
    private javax.swing.JComboBox<String> box_tratamiento_inicial;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_porcentaje;
    private javax.swing.JTextField txt_fecha_accidente;
    private javax.swing.JTextField txt_hora_accidente;
    private javax.swing.JTextArea txt_mecanismo_accidente;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_registro;
    // End of variables declaration//GEN-END:variables
}
