/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Forms;

import Controlador.PacienteDAO;
import Modelo.Paciente;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Usuario
 */
public class IngresoPacientes extends javax.swing.JPanel {

    //Variable para agregar a la DB la seleccion del RadioButton
    private String opcionSeleccionada;
    ButtonGroup buttonGroup = new ButtonGroup();
    //Clasees que contienen los metodos para manejar la DB
    PacienteDAO paciente = new PacienteDAO();
    Paciente p = new Paciente();

    public IngresoPacientes() {
        initComponents();
        setOpaque(false);
        setVisible(true);

        //Agregando imagen para el boton guardar y redimensionandola -
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/icon/guardar.png"));

        // Escalar la imagen al tamaño deseado (ajustar valores segun se necesite)
        Image imagen = icono.getImage();
        Image nuevaImagen = imagen.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);

        btnGuardar.setIcon(new javax.swing.ImageIcon(nuevaImagen));

        //Agregando a un Group los RadioButtons
        buttonGroup.add(ButtonMenos500);
        buttonGroup.add(Buttonentre);
        buttonGroup.add(ButtonEntre1000);
        buttonGroup.add(ButtonMas2000);

        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener el botón seleccionado
                JRadioButton selectedButton = (JRadioButton) e.getSource();
                opcionSeleccionada = selectedButton.getText();
            }
        };

        // Agregar el ActionListener a cada RadioButton
        ButtonMenos500.addActionListener(actionListener);
        Buttonentre.addActionListener(actionListener);
        ButtonEntre1000.addActionListener(actionListener);
        ButtonMas2000.addActionListener(actionListener);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        PanelRegistroMedico = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaIngresoH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaIngresoQ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaEgresoQ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClinicaQ = new javax.swing.JTextField();
        PanelDatosPersonales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        txtApellidosPaciente = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtSexo = new javax.swing.JComboBox<>();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtAldea = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtNoMiembros = new javax.swing.JTextField();
        txtLugarOcupa = new javax.swing.JTextField();
        txtAdultos = new javax.swing.JTextField();
        txtNinos = new javax.swing.JTextField();
        txtNoHijos = new javax.swing.JTextField();
        ButtonMenos500 = new javax.swing.JRadioButton();
        Buttonentre = new javax.swing.JRadioButton();
        ButtonEntre1000 = new javax.swing.JRadioButton();
        ButtonMas2000 = new javax.swing.JRadioButton();
        txtReferido = new javax.swing.JTextField();
        txtEncargado = new javax.swing.JTextField();
        txtParentesco = new javax.swing.JTextField();
        txtEdadEncargado = new javax.swing.JTextField();
        txtEscolaridad = new javax.swing.JComboBox<>();
        txtOcupacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        PanelRegistroMedico.setBackground(new java.awt.Color(0, 102, 102));
        PanelRegistroMedico.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REGISTRO MEDICO Y CLINICO");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO MEDICO:");

        txtRegistro.setBackground(new java.awt.Color(204, 204, 204));
        txtRegistro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FECHA INGRESO AL HOSPITAL:");

        txtFechaIngresoH.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaIngresoH.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA INGRESO UNIDAD \nDE QUEMADOS:");

        txtFechaIngresoQ.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaIngresoQ.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA EGRESO UNIDAD DE QUEMADOS:");

        txtFechaEgresoQ.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaEgresoQ.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FECHA INIDIO CLINICA DE QUEMADURAS REHABILITACION:");

        txtClinicaQ.setBackground(new java.awt.Color(204, 204, 204));
        txtClinicaQ.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelRegistroMedicoLayout = new javax.swing.GroupLayout(PanelRegistroMedico);
        PanelRegistroMedico.setLayout(PanelRegistroMedicoLayout);
        PanelRegistroMedicoLayout.setHorizontalGroup(
            PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClinicaQ))
                    .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                        .addGroup(PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaIngresoQ, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addGroup(PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegistroMedicoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaIngresoH))
                            .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaEgresoQ, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
            .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRegistroMedicoLayout.setVerticalGroup(
            PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroMedicoLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtFechaIngresoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaIngresoQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaEgresoQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(PanelRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtClinicaQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        PanelDatosPersonales.setBackground(new java.awt.Color(0, 102, 102));
        PanelDatosPersonales.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATOS PERSONALES");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMBRE:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("APELLIDOS:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EDAD:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SEXO:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FECHA DE NACIMIENTO:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DIRECCION EXACTA:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ALDEA:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MUNICIPIO:");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DEPARTAMENTO:");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TELEFONO:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NO. DE MIEMBROS EN LA FAMILIA:");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ADULTOS:");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("NIÑOS:");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NO. DE HIJOS:");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("LUGAR QUE OCUPA:");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("INGRESO MENSUAL:");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("REFERIDO POR:");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("ENCARGADO:");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PARENTESCO:");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("EDAD:");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ESCOLARIDAD:");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("OCUPACION:");

        txtNombrePaciente.setBackground(new java.awt.Color(204, 204, 204));
        txtNombrePaciente.setForeground(new java.awt.Color(0, 0, 0));

        txtApellidosPaciente.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidosPaciente.setForeground(new java.awt.Color(0, 0, 0));

        txtEdad.setBackground(new java.awt.Color(204, 204, 204));
        txtEdad.setForeground(new java.awt.Color(0, 0, 0));

        txtSexo.setBackground(new java.awt.Color(204, 204, 204));
        txtSexo.setForeground(new java.awt.Color(204, 204, 204));
        txtSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        txtFechaNacimiento.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));

        txtDireccion.setBackground(new java.awt.Color(204, 204, 204));
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));

        txtAldea.setBackground(new java.awt.Color(204, 204, 204));
        txtAldea.setForeground(new java.awt.Color(0, 0, 0));

        txtMunicipio.setBackground(new java.awt.Color(204, 204, 204));
        txtMunicipio.setForeground(new java.awt.Color(0, 0, 0));

        txtDepartamento.setBackground(new java.awt.Color(204, 204, 204));
        txtDepartamento.setForeground(new java.awt.Color(0, 0, 0));

        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));

        txtNoMiembros.setBackground(new java.awt.Color(204, 204, 204));
        txtNoMiembros.setForeground(new java.awt.Color(0, 0, 0));

        txtLugarOcupa.setBackground(new java.awt.Color(204, 204, 204));
        txtLugarOcupa.setForeground(new java.awt.Color(0, 0, 0));

        txtAdultos.setBackground(new java.awt.Color(204, 204, 204));
        txtAdultos.setForeground(new java.awt.Color(0, 0, 0));

        txtNinos.setBackground(new java.awt.Color(204, 204, 204));
        txtNinos.setForeground(new java.awt.Color(0, 0, 0));

        txtNoHijos.setBackground(new java.awt.Color(204, 204, 204));
        txtNoHijos.setForeground(new java.awt.Color(0, 0, 0));

        ButtonMenos500.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMenos500.setText("< Q500");

        Buttonentre.setForeground(new java.awt.Color(255, 255, 255));
        Buttonentre.setText("Q500 - Q 1000");

        ButtonEntre1000.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEntre1000.setText("Q 1000 - Q 2000");

        ButtonMas2000.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMas2000.setText("> Q 2000");

        txtReferido.setBackground(new java.awt.Color(204, 204, 204));
        txtReferido.setForeground(new java.awt.Color(0, 0, 0));

        txtEncargado.setBackground(new java.awt.Color(204, 204, 204));
        txtEncargado.setForeground(new java.awt.Color(0, 0, 0));

        txtParentesco.setBackground(new java.awt.Color(204, 204, 204));
        txtParentesco.setForeground(new java.awt.Color(0, 0, 0));

        txtEdadEncargado.setBackground(new java.awt.Color(204, 204, 204));
        txtEdadEncargado.setForeground(new java.awt.Color(0, 0, 0));

        txtEscolaridad.setBackground(new java.awt.Color(204, 204, 204));
        txtEscolaridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primaria", "Basico", "Diversificado", "No Sabe Leer ni Escribir" }));

        txtOcupacion.setBackground(new java.awt.Color(204, 204, 204));
        txtOcupacion.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(46, 68, 82));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosPersonalesLayout = new javax.swing.GroupLayout(PanelDatosPersonales);
        PanelDatosPersonales.setLayout(PanelDatosPersonalesLayout);
        PanelDatosPersonalesLayout.setHorizontalGroup(
            PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNinos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNoMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtNoHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(txtLugarOcupa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))))
                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEdadEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtReferido))
                            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                        .addGap(314, 314, 314)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOcupacion))
                                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(27, 27, 27)
                                        .addComponent(ButtonMenos500)
                                        .addGap(50, 50, 50)
                                        .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                                .addComponent(Buttonentre)
                                                .addGap(36, 36, 36)
                                                .addComponent(ButtonEntre1000)
                                                .addGap(64, 64, 64)
                                                .addComponent(ButtonMas2000))))
                                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidosPaciente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosPersonalesLayout.createSequentialGroup()
                                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAldea, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 21, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombrePaciente))))
                    .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        PanelDatosPersonalesLayout.setVerticalGroup(
            PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtApellidosPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAldea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtNoMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtLugarOcupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ButtonMenos500)
                    .addComponent(Buttonentre)
                    .addComponent(ButtonEntre1000)
                    .addComponent(ButtonMas2000))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtReferido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(txtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelRegistroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRegistroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        agregar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    //metodo para agregar.
    void agregar() {

        try {
            // Obtener la fecha desde el JTextField
            String fechaIngresoHStr = txtFechaIngresoH.getText();
            String fechaIngresoUnidad = txtFechaIngresoQ.getText();
            String fechaEgresoUnidad = txtFechaEgresoQ.getText();
            String fechaNacimiento = txtFechaNacimiento.getText();

            // Convertir la cadena de texto a LocalDate
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate fechaIngresoH = LocalDate.parse(fechaIngresoHStr, formatter);
            LocalDate fechaIngresoQ = LocalDate.parse(fechaIngresoUnidad, formatter);
            LocalDate fechaEgresoQ = LocalDate.parse(fechaEgresoUnidad, formatter);
            LocalDate fechaNacim = LocalDate.parse(fechaNacimiento, formatter);

            //Array para almacenar los valores de todos los TextFields 
            Object[] ob = new Object[]{
                txtRegistro.getText(), fechaIngresoH, fechaIngresoQ,
                fechaEgresoQ, txtNombrePaciente.getText(), txtApellidosPaciente.getText(),
                Integer.parseInt(txtEdad.getText()), (String) txtSexo.getSelectedItem(),
                fechaNacim, txtDireccion.getText(), txtAldea.getText(),
                txtMunicipio.getText(), txtDepartamento.getText(), Integer.parseInt(txtTelefono.getText()),
                Integer.parseInt(txtNoMiembros.getText()), Integer.parseInt(txtAdultos.getText()),
                Integer.parseInt(txtNinos.getText()), Integer.parseInt(txtNoHijos.getText()), Integer.parseInt(txtLugarOcupa.getText()),
                opcionSeleccionada, txtReferido.getText(), txtEncargado.getText(),
                txtParentesco.getText(), Integer.parseInt(txtEdadEncargado.getText()),
                (String) txtEscolaridad.getSelectedItem(), txtOcupacion.getText()
            };

            paciente.agregar(ob);
            //Revisa si el campo de Registro medico esta vacio, y lanza error si es asi. 
            if (txtRegistro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El campo 'Registro Médico' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                //Si todo esta correcto se lanza un mensaje de afirmacion y se limpian los campos 
                JOptionPane.showMessageDialog(null, "Paciente Registrado con exito!");
                limpiarCampos();
            }
        } catch (Exception e) {
            // Si hay una excepción, mostrar un cuadro de diálogo de error
            JOptionPane.showMessageDialog(null, "Error al registrar al paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprimir la traza de la excepción en la consola (puedes quitar esto en producción)
        }

    }

    //metodo para limpiar los campos
    void limpiarCampos() {
        txtRegistro.setText("");
        txtFechaIngresoH.setText("");
        txtFechaIngresoQ.setText("");
        txtFechaEgresoQ.setText("");
        txtNombrePaciente.setText("");
        txtApellidosPaciente.setText("");
        txtEdad.setText("");
        txtSexo.setSelectedIndex(0);
        txtFechaNacimiento.setText("");
        txtDireccion.setText("");
        txtAldea.setText("");
        txtMunicipio.setText("");
        txtDepartamento.setText("");
        txtTelefono.setText("");
        txtNoMiembros.setText("");
        txtAdultos.setText("");
        txtNinos.setText("");
        txtNoHijos.setText("");
        txtLugarOcupa.setText("");
        buttonGroup.clearSelection();
        txtReferido.setText("");
        txtEncargado.setText("");
        txtParentesco.setText("");
        txtEdadEncargado.setText("");
        txtEscolaridad.setSelectedIndex(0);
        txtOcupacion.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ButtonEntre1000;
    private javax.swing.JRadioButton ButtonMas2000;
    private javax.swing.JRadioButton ButtonMenos500;
    private javax.swing.JRadioButton Buttonentre;
    private javax.swing.JPanel PanelDatosPersonales;
    private javax.swing.JPanel PanelRegistroMedico;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdultos;
    private javax.swing.JTextField txtAldea;
    private javax.swing.JTextField txtApellidosPaciente;
    private javax.swing.JTextField txtClinicaQ;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdadEncargado;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JComboBox<String> txtEscolaridad;
    private javax.swing.JTextField txtFechaEgresoQ;
    private javax.swing.JTextField txtFechaIngresoH;
    private javax.swing.JTextField txtFechaIngresoQ;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtLugarOcupa;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNinos;
    private javax.swing.JTextField txtNoHijos;
    private javax.swing.JTextField txtNoMiembros;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtParentesco;
    private javax.swing.JTextField txtReferido;
    private javax.swing.JTextField txtRegistro;
    private javax.swing.JComboBox<String> txtSexo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
