/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.Forms;

import Controlador.PacienteDAO;
import Modelo.Paciente;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Usuario
 */
public class Quemaduras extends javax.swing.JPanel {

    //Variable para agregar a la DB la seleccion del RadioButton
    private String opcionSeleccionada;
    ButtonGroup buttonGroup = new ButtonGroup();
    //Clasees que contienen los metodos para manejar la DB
    PacienteDAO paciente = new PacienteDAO();
    Paciente p = new Paciente();

    public Quemaduras() {
        initComponents();
        setOpaque(false);
        setVisible(true);

        //Agregando imagen para el boton guardar y redimensionandola -
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/icon/guardar.png"));

        // Escalar la imagen al tamaño deseado (ajustar valores segun se necesite)
        Image imagen = icono.getImage();
        Image nuevaImagen = imagen.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);

        btnGuardar.setIcon(new javax.swing.ImageIcon(nuevaImagen));


        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener el botón seleccionado
                JRadioButton selectedButton = (JRadioButton) e.getSource();
                opcionSeleccionada = selectedButton.getText();
            }
        };


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        PanelDatosPersonales = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        PanelDatosPersonales.setBackground(new java.awt.Color(0, 102, 102));
        PanelDatosPersonales.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setBackground(new java.awt.Color(46, 68, 82));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosPersonalesLayout = new javax.swing.GroupLayout(PanelDatosPersonales);
        PanelDatosPersonales.setLayout(PanelDatosPersonalesLayout);
        PanelDatosPersonalesLayout.setHorizontalGroup(
            PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosPersonalesLayout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        PanelDatosPersonalesLayout.setVerticalGroup(
            PanelDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap(597, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PanelDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDatosPersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //agregar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    //metodo para agregar.
    /*void agregar() {

        try {
            // Obtener la fecha desde el JTextField
            String fechaIngresoHStr = txtFechaIngresoH.getText();
            String fechaIngresoUnidad = txtFechaIngresoQ.getText();
            String fechaEgresoUnidad = txtFechaEgresoQ.getText();
            String fechaNacimiento = txtFechaNacimiento.getText();

            // Convertir la cadena de texto a LocalDate
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate fechaIngresoH = LocalDate.parse(fechaIngresoHStr, formatter);
            LocalDate fechaIngresoQ = LocalDate.parse(fechaIngresoUnidad, formatter);
            LocalDate fechaEgresoQ = LocalDate.parse(fechaEgresoUnidad, formatter);
            LocalDate fechaNacim = LocalDate.parse(fechaNacimiento, formatter);

            //Array para almacenar los valores de todos los TextFields 
            Object[] ob = new Object[]{
                txtRegistro.getText(), fechaIngresoH, fechaIngresoQ,
                fechaEgresoQ, txtNombrePaciente.getText(), txtApellidosPaciente.getText(),
                Integer.parseInt(txtEdad.getText()), (String) txtSexo.getSelectedItem(),
                fechaNacim, txtDireccion.getText(), txtAldea.getText(),
                txtMunicipio.getText(), txtDepartamento.getText(), Integer.parseInt(txtTelefono.getText()),
                Integer.parseInt(txtNoMiembros.getText()), Integer.parseInt(txtAdultos.getText()),
                Integer.parseInt(txtNinos.getText()), Integer.parseInt(txtNoHijos.getText()), Integer.parseInt(txtLugarOcupa.getText()),
                opcionSeleccionada, txtReferido.getText(), txtEncargado.getText(),
                txtParentesco.getText(), Integer.parseInt(txtEdadEncargado.getText()),
                (String) txtEscolaridad.getSelectedItem(), txtOcupacion.getText()
            };

            paciente.agregar(ob);
            //Revisa si el campo de Registro medico esta vacio, y lanza error si es asi. 
            if (txtRegistro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El campo 'Registro Médico' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                //Si todo esta correcto se lanza un mensaje de afirmacion y se limpian los campos 
                JOptionPane.showMessageDialog(null, "Paciente Registrado con exito!");
                limpiarCampos();
            }
        } catch (Exception e) {
            // Si hay una excepción, mostrar un cuadro de diálogo de error
            JOptionPane.showMessageDialog(null, "Error al registrar al paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprimir la traza de la excepción en la consola (puedes quitar esto en producción)
        }

    }*/

    //metodo para limpiar los campos
    /*void limpiarCampos() {
        txtRegistro.setText("");
        txtFechaIngresoH.setText("");
        txtFechaIngresoQ.setText("");
        txtFechaEgresoQ.setText("");
        txtNombrePaciente.setText("");
        txtApellidosPaciente.setText("");
        txtEdad.setText("");
        txtSexo.setSelectedIndex(0);
        txtFechaNacimiento.setText("");
        txtDireccion.setText("");
        txtAldea.setText("");
        txtMunicipio.setText("");
        txtDepartamento.setText("");
        txtTelefono.setText("");
        txtNoMiembros.setText("");
        txtAdultos.setText("");
        txtNinos.setText("");
        txtNoHijos.setText("");
        txtLugarOcupa.setText("");
        buttonGroup.clearSelection();
        txtReferido.setText("");
        txtEncargado.setText("");
        txtParentesco.setText("");
        txtEdadEncargado.setText("");
        txtEscolaridad.setSelectedIndex(0);
        txtOcupacion.setText("");
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatosPersonales;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables
}
